### ISSUE TITLE
Can't push my challenge to repo

### ISSUE THREAD

**Issue by henrikaxelsen** [TokenEngineeringCommunity/RAI-Digital-Twin-Workshops#2]
Not sure what goes wrong, but I am having trouble pushing the commit: [challenge_1_HAX.md](https://github.com/TokenEngineeringCommunity/RAI-Digital-Twin-Workshops/files/7511693/challenge_1_HAX.md)

**Comment by danlessa** [comment]
@henrikaxelsen the procedure is as follows:

1. Fork this repo
2. Modify the forked repo (eg. `henrikaxelsen/RAI-Digital-Twin-Workshops`)
3. Commit and push the forked repo
4. Create a Pull Request to this repo

Let me know if works!
